#!/bin/sh
systemctl enable odroid-tweaks

# Run OS File updates
cp /media/boot/boot.ini /media/boot/boot.ini.old
cp /media/boot/config.ini /media/boot/config.ini.old || true
cp /usr/share/bootini/boot.ini /media/boot/boot.ini
cp /usr/share/bootini/config.ini /media/boot/config.ini

rm -fr /media/boot/boot.ini.default

#/usr/sbin/update-initramfs -c -k `uname -r`
#mkimage -A arm64 -O linux -T ramdisk -C none -a 0 -e 0 -n "uInitrd" -d /boot/initrd.img-`uname -r` /boot/uInitrd-`uname -r`
#cp /boot/uInitrd-`uname -r` /media/boot/uInitrd

echo "A new boot.ini is installed." 
echo "Any changes to boot.ini is lost, such as display configuration" 
echo "Persistent custom settings from /media/boot/boot.ini.default have been restored"
echo "For reference your old boot.ini is saved to /media/boot/boot.ini.old"

#usermod -a -G sys odroid || true
